"""User's is_editor flag.

Revision ID: 637c9d1295da
Revises: 
Create Date: 2023-05-07 16:03:57.575766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637c9d1295da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_editor', sa.Boolean(), nullable=True, default=False))
        #batch_op.execute("UPDATE user SET is_editor = false")
        #batch_op.alter_column('user', 'is_editor', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_editor')

    # ### end Alembic commands ###
