"""User.[email, language, is_student, is_teacher] not nullable

Revision ID: 819e7f13bde1
Revises: f5706673a23a
Create Date: 2023-05-15 17:54:30.233366

"""
import random
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819e7f13bde1'
down_revision = 'f5706673a23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.execute(f"UPDATE user SET email = RANDOM()")
        batch_op.execute("UPDATE user SET language = 'en'")
        batch_op.execute("UPDATE user SET is_student = true")
        batch_op.execute("UPDATE user SET is_teacher = false")
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('is_student',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_student',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
