"""User += email, language, is_student, is_teacher

Revision ID: f5706673a23a
Revises: fbc079b4cb52
Create Date: 2023-05-15 17:48:26.441257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5706673a23a'
down_revision = 'fbc079b4cb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_student', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_teacher', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint("uq_user_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_email", type_='unique')
        batch_op.drop_column('is_teacher')
        batch_op.drop_column('is_student')
        batch_op.drop_column('language')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
