"""No more backref for scores.

Revision ID: fad29dc6dc09
Revises: 637c9d1295da
Create Date: 2023-05-11 14:26:48.117459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad29dc6dc09'
down_revision = '637c9d1295da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_editor',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_editor',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
